
@startuml
title nadesiko 2019
box "大学/高校/ユース" 
	participant "神奈川大" as ku #lightblue
	participant "早稲田大" as wu #lightblue
	participant "関西学院大" as kgu #lightblue
	participant "順天堂大" as juu #lightblue
	participant "仙台大" as seu #lightblue
	participant "関東学院大" as tgu #lightblue
	participant "東京國際大" as tiu #lightblue
	participant "尚美学園大" as sbu  #lightblue
	participant "山梨学院大" as ygu  #lightblue
	participant "筑波大" as tu  #lightblue
	participant "鹿児島女子高" as kjh #lightblue
	participant "修徳高" as shh #lightblue
	participant "追手門学院高" as ogh #lightblue
	participant "作陽高" as syh #lightblue
	participant "常葉大付橘高" as tth #lightblue
	participant "鎮西学院高" as cgh #lightblue

    
	participant "アルビU-18" as anu #lightblue
	participant "ちふれマリ" as cem #lightblue
end box
box "一部" 
	participant "ベレーザ" as nb #lightgreen
	participant "INAC" as il #red
	participant "ノジマ" as ns #pink
	participant "レッズ" as ur #red
	participant "アルビ" as an #ffa000
	participant "ジェフ" as jl #f0ff00
	participant "パルセイロ" as np #ff8000
	participant "ベガルタ" as vs #yellow
	participant "日体大" as nf #LightBlue
	participant "くノ一" as ik  #lightgreen
end box

box "二部" 
	participant "セレッソL" as cl #pink
	participant "ニッパツ" as ny #LightBlue
	participant "ちふれ" as ce #white
	participant "オルカ" as ok #lightblue
	participant "ハリマ" as ha #LightBlue
	participant "愛媛FC" as ef #magenta
	participant "静産" as si #lightgreen
	participant "スフィーダ" as ss #LightBlue
	participant "バニーズ" as bk #red
	participant "大和" as ys #red
end box

box "チャレンジ" 
	participant "湯郷" as yb #LightBlue
	participant "十文字" as jv #LightBlue
	participant "JFA福島" as jf #LightBlue
	participant "アンジュ" as ah #magenta
	participant "吉備國際" as co #pink
	participant "NGU" as nn #lightblue
	participant "新潟医療" as nd #ff8000
	participant "北海道" as nh #pink
	participant "コノミヤ" as kt #lightgreen
	participant "セレッソG" as cg #pink
	participant "常盤木" as tk #lightgreen
	participant "つくば" as tf #lightblue
end box

box "地域"
	participant "群馬WS" as gh #red
	participant "鷲塚SS" as ws #lightblue
	participant "HFC" as hf #lightblue
	participant "ルクレ" as my #lightblue
	participant "ヴィアティン見え" as vm #lightblue
end box

box "海外"
	participant "Suwon" as sw #lightblue
	participant "KSPO" as ks #lightblue
	participant "Mainz" as sm #lightblue
	participant "canberra" as os1 #lightblue
    participant "Hyundai" as os2 #lightblue
	participant "BaysideU" as os3  #lightblue
end box

box "その他"
	participant "未定" as un 
participant "引退" as re 
end box

'-----1

'11 beleza nb
'jv <- nb:FW 鳥海 由佳
'vs <- nb:MF 隅田 凜
'ce <- nb:MF 上辻 佑実
'ys <- nb:GK 田中 桃子
nb <- jf:MF 遠藤 純

'12 inac il
il <- ns:GK 田尻 有美
il <- wu:FW 河野 朱里
il <- wu:DF 三浦 紗津紀
il <- an:MF	八坂 芽依
il <- co:MF	吉田 凪沙
'ha <- il:DF 杉田 めい

'13 nojima ns
'ks <- ns:DF 吉見 夏稀
'ok <- ns:FW 正野 可菜子
ns <- jl:DF 櫻本 尚子
ns <- np:MF 中野 真奈美
ns <- vs:MF 佐々木 美和
ns <- nf:MF 平田 ひかり
ns <- nf:DF 大賀 理紗子
ns <- nf:GK 森田 有加里
ns <- kjh:MF 松田 早和
ns <- ku:MF 鈴木 綾華
ns <- ku:DF 大隅 沙耶

're <- ns:GK 田尻 有美
're <- ns:DF 臼井 理恵
're <- ns:FW 工藤 麻未
're <- ns:DF 高木 ひかり

'14 reds ur
'ce <- ur:MF 木崎 あおい 
'ok <- ur:MF 山守 杏奈
'vs <- ur:FW 白木 星
ur <- nf:FW 植村 祥子
ur <- tk:MF 柴山 史菜
ur <- wu:MF 柳澤 紗希
ur <- tu:MF 水谷 有希
'ny <- ur:DF 長嶋 洸

'15 albi an
'ny <- an:DF 小原 由梨愛
'un <- an:FW 川崎 咲耶
'un <- an:GK 福村 香奈絵
're <- an:DF 久保田 麻友 
an <- jf:MF 武田 あすみ
an <- co:MF 松原 志歩
an <- nd:DF 池田 玲奈
an <- tk:MF 加藤 栞
an <- kgu:FW 石淵 萌実
an <- ku:MF 瀧澤 莉央
an <- anu:MF 白井 ひめ乃
'nd <- anu:MF 中江 萌

'16 jef jl 
'ce <- jl:MF 深澤 里沙
'ns <- jl:DF 櫻本 尚子
jl <- ss:DF 田中 真理子

'17 nagano np
'ce <- np:MF 中村 ゆしか
'ce <- np:MF 木下 栞
'ce <- np:MF 齊藤 あかね
'ce <- np:MF 大宮 玲央奈
'ny <- np:DF 坂本 理保
'ny <- np:GK 望月 ありさ
'ns <- np:MF 中野 真奈美
'ah <- np:MF 神田 若帆
'ah <- np:DF 池崎 愛
'gh <- np:GK 小髙 愛理
np <- yb:FW 濱本 まりん
np <- yb:MF 巴月 優希

'18 sendai vs
vs <- nb:MF 隅田 凜
vs <- ur:FW 白木 星
vs <- jl:MF 佐藤 瑞夏

'sw <- vs:FW 櫨 まどか
'ns <- vs:MF 佐々木 美和

'19 nittai nf
'ns <- nf:MF 平田 ひかり
'ns <- nf:DF 大賀 理紗子
'ns <- nf:GK 森田 有加里
'my <- nf:MF 後藤 亜弥
re <- nf:MF 石井 千晴
re <- nf:DF 櫻井 麻友佳

'1x iga ik
ik <- il:FW 道上 彩花
ik <- jl:FW 三橋 明香
ik <- jl:MF 安齋 結花
ik <- np:FW 西川 明花
're <- ik:FW 神山　ゆい

'-----2

'cellezo co

'nippatsu seaguls ny
're <- ny:DF 山川 夏輝
ny <- shh:MF 小林 ひなた
ny <- juu:MF 浦田 佳穂
ny <- np:DF 坂本 理保
ny <- np:GK 望月 ありさ
're <- ny:DF 金澤 真美
're <- ny:FW 石原 愛海
're <- ny:MF 加賀 孝子
're <- ny:MF 佐藤 渚
're <- ny:MF 岩木 綾乃
're <- ny:MF 中村みづき
ny <- seu:GK 越後 希波
ny <- sm:FW 瀬川 邑那
ny <- ur:DF 長嶋 洸
ny <- an:DF 小原 由梨愛
'un <- ny:GK 新井 翠
'an <- co:MF 松原 志歩


'chifure ce
ce <- nb:MF 上辻 佑実
ce <- il:GK 福元 美穂
ce <- ur:MF 木崎 あおい 
ce <- jl:MF 深澤 里沙
ce <- np:MF 中村 ゆしか 
ce <- np:MF 木下 栞 
ce <- np:MF 齊藤 あかね
ce <- np:MF 大宮 玲央奈
ce <- ss:FW 山本 菜桜美
ce <- yb:FW 杉山 貴子
ce <- co:DF 呉屋 絵理子
ce <- os2:MF 長野 風花
un <- ce:MF 永島 自然


'ha <- ce:GK 高橋 麻美
'ha <- ce:MF 中野 里乃
'jv <- ce:MF 又吉 果奈
'jv <- cem:DF 堤 夏穂
'jv <- ce:DF 村社 汐理
'yb <- ce:MF 竹ノ谷 好美
'wu <- ce:FW 土居 明日香
'ys <- ce:DF 岸 みのり

'	"オルカ" as ok #lightblue
ok <- tgu:FW 齊藤 彩花
ok <- tiu:DF 新井 純奈
ok <- tiu:GK 清水 栞
ok <- wu:DF 渡部 那月
ok <- syh:DF 山田 優衣
ok <- ns:FW 正野 可菜子
ok <- ks:MF 南山 千明
ok <- ur:MF 山守 杏奈
'vm <- ok:DF 小林 映里奈

un <- ok:MF 藤田 のぞみ
un <- ok:MF 西尾 麻奈美

'	"ハリマ" as ha #LightBlue
ha <- il:DF 杉田 めい
ha <- ce:GK 高橋 麻美
ha <- ce:MF 中野 里乃
ha <- yb:FW 長澤 優芽


un <- ha:DF STEPHANIE Kay Spiekerman
un <- ha:MF 濱川 菜央
un <- ha:GK 伊藤 千央
un <- ha:DF 市川 愛雪
un <- ha:MF 山本 早織
un <- ha:MF 上嶋 瞳
un <- ha:FW 矢次 亜佳音
un <- ha:MF 西野 有香
un <- ha:DF 佐野 早紀
un <- ha:FW 桑原 茜
un <- ha:GK 切畑 琴乃

'	"愛媛FC" as ef #magenta
ef <- jl:MF 横山 亜依
un <- ef:DF 假屋 麻衣子
un <- ef:MF 小川 真名美
un <- ef:DF 阿部 理絵
un <- ef:FW 立花 真美
un <- ef:MF 中村 栞
un <- ef:FW 金井 奈苗
un <- ef:MF 江尻 莉緒



'	"静産" as si #lightgreen
si <- nf:FW 小針 舞夏
si <- nf:MF 島村 友妃子
si <- os3:DF 武田 ありさ
si <- os3:DF 平野 里菜
si <- nf:DF 山中 沙織
si <- ws:GK 高橋　美春

'	"スフィーダ" as ss #LightBlue
ss <- sbu:MF 中山 さつき(
si <- ygu:DF 金子 ゆい
'jv <- ss:MF 花桐 なおみ
'jl <- ss:DF 田中 真理子
'jv <- ss:MF 伊藤 千梅
un <- ss:FW 犛山 菜々恵

're <- ss:DF 橘木 友理恵


'	"バニーズ" as bk #red
bk <- il:MF 平塚 万貴
bk <- tth:MF 小池 真理
un <- bk:DF 樋口 里穂
un <- bk:MF 長井 咲季
un <- bk:MF 酒井 美鈴

're <- bk:FW 西川 樹
're <- bk:FW 仙石 來夢
're <- bk:GK 田中 幸奈

'	"大和シルフィード" as ys #red
ys <- nf:FW 中野 ひかり
ys <- nf:DF 菅能 夏海
ys <- ce:DF 岸 みのり
ys <- ah:DF 櫻林 亜佐子
ys <- sbu:DF 本間 麻椰
ys <- cgh:MF 中村 怜愛
ys <- nb:GK 田中 桃子

'ah <- ys:GK 田中 幸奈

're <- ys:DF 中川 茉子
're <- ys:FW 村山 百花
're <- ys:DF 吉川 小夜子
'hf <- ys:DF 千田 満里奈

'-----c
' "湯郷" as yb #LightBlue
yb <- ce:MF 竹ノ谷 好美
'ha <- yb:FW 長澤 優芽

'"十文字" as jv #LightBlue
jv <- nb:FW 鳥海 由佳
jv <- ce:MF 又吉 果奈
jv <- cem:DF 堤 夏穂
jv <- ce:DF 村社 汐理
jv <- ss:MF 伊藤 千梅
jv <- ss:MF 花桐 なおみ

' "JFA福島" as jf #LightBlue

' "アンジュ" as ah #magenta
ah <- ys:GK 田中 幸奈
ah <- np:MF 神田 若帆
ah <- np:DF 池崎 愛
' "吉備國際" as co #pink
' "NGU" as nn #lightblue
' "新潟医療" as nd #ff8000
' "北海道" as nh #pink
' "コノミヤ" as kt #lightgreen
' "セレッソG" as cg #pink
' "常盤木" as tk #lightgreen
' "つくば" as tf #lightblue

'----地域
hf <- ys:DF 千田 満里奈
my <- nf:MF 後藤 亜弥
gh <- np:GK 小髙 愛理
vm <- ok:DF 小林 映里奈


'-----海外など移籍
nd <- anu:MF 中江 萌
ks <- ns:DF 吉見 夏稀
sw <- vs:FW 櫨 まどか
wu <- ce:FW 土居 明日香


'-----引退/未定
un <- an:FW 川崎 咲耶
un <- an:GK 福村 香奈絵
un <- ny:GK 新井 翠



're <- ns:GK 田尻 有美
re <- ns:DF 臼井 理恵
re <- ns:FW 工藤 麻未
re <- ns:DF 高木 ひかり

re <- an:DF 久保田 麻友 

re <- np:MF 髙橋 奈々

re <- vs:DF 千葉 梢恵


re <- ik:FW 神山　ゆい

re <- ny:DF 山川 夏輝
re <- ny:DF 金澤 真美
re <- ny:FW 石原 愛海
re <- ny:MF 加賀 孝子
re <- ny:MF 佐藤 渚
re <- ny:MF 岩木 綾乃
re <- ny:MF 中村みづき

re <- ok:GK 有馬 静佳
re <- ok:DF 赤荻 美佳
re <- ok:DF 小林 映里奈

re <- ss:DF 橘木 友理恵

re <- bk:FW 西川 樹
re <- bk:FW 仙石 來夢
re <- bk:GK 田中 幸奈

re <- ys:DF 中川 茉子
re <- ys:FW 村山 百花
re <- ys:DF 吉川 小夜子


@enduml